title: Data, code and science
author: Maximilian Konzack
email: maximilian.konzack@idiv.de
description: >- # this means to ignore newlines until "baseurl:"
  A blog about wrangling data, crafting code and communicating open science.
  Feel free to subscribe the feed.xml.
baseurl: '/blog' # the subpath of your site, e.g. /blog
url: "https://komax.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  komax

# Build settings
markdown: kramdown
#theme: minima
remote_theme: komax/minima-reboot
plugins:
  - jekyll-feed

permalink: /:categories/:title/

footer_icons:
- username: komax
  url: https://github.com/komax
  icon: icon-github.svg

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - minima.reboot.gemspec
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
